node {
  name: "zeros_like"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_HALF
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_HALF
        tensor_shape {
          dim {
            size: 3
          }
          dim {
            size: 12
          }
        }
        half_val: 0
      }
    }
  }
}
library {
}
