node {
  name: "in_0"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 1
          }
          dim {
            size: 2
          }
          dim {
            size: 3
          }
        }
        tensor_content: "~^G?L\033M?\236p9?\220ol>\356%:?X\2708>"
      }
    }
  }
}
node {
  name: "in_0/read"
  op: "Identity"
  input: "in_0"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_0"
      }
    }
  }
}
node {
  name: "is_non_decreasing/Reshape/shape"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 1
          }
        }
        int_val: -1
      }
    }
  }
}
node {
  name: "is_non_decreasing/Reshape"
  op: "Reshape"
  input: "in_0/read"
  input: "is_non_decreasing/Reshape/shape"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "Tshape"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "is_non_decreasing/Size"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 6
      }
    }
  }
}
node {
  name: "is_non_decreasing/Less/y"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
}
node {
  name: "is_non_decreasing/Less"
  op: "Less"
  input: "is_non_decreasing/Size"
  input: "is_non_decreasing/Less/y"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "is_non_decreasing/Shape"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 1
          }
        }
        int_val: 6
      }
    }
  }
}
node {
  name: "is_non_decreasing/sub/y"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "is_non_decreasing/sub"
  op: "Sub"
  input: "is_non_decreasing/Shape"
  input: "is_non_decreasing/sub/y"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "is_non_decreasing/cond/Switch"
  op: "Switch"
  input: "is_non_decreasing/Less"
  input: "is_non_decreasing/Less"
  attr {
    key: "T"
    value {
      type: DT_BOOL
    }
  }
}
node {
  name: "is_non_decreasing/cond/switch_t"
  op: "Identity"
  input: "is_non_decreasing/cond/Switch:1"
  attr {
    key: "T"
    value {
      type: DT_BOOL
    }
  }
}
node {
  name: "is_non_decreasing/cond/switch_f"
  op: "Identity"
  input: "is_non_decreasing/cond/Switch"
  attr {
    key: "T"
    value {
      type: DT_BOOL
    }
  }
}
node {
  name: "is_non_decreasing/cond/pred_id"
  op: "Identity"
  input: "is_non_decreasing/Less"
  attr {
    key: "T"
    value {
      type: DT_BOOL
    }
  }
}
node {
  name: "is_non_decreasing/cond/Const"
  op: "Const"
  input: "^is_non_decreasing/cond/switch_t"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
          }
        }
      }
    }
  }
}
node {
  name: "is_non_decreasing/cond/add/x"
  op: "Const"
  input: "^is_non_decreasing/cond/switch_f"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 1
          }
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "is_non_decreasing/cond/add"
  op: "AddV2"
  input: "is_non_decreasing/cond/add/x"
  input: "is_non_decreasing/cond/add/Switch"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "is_non_decreasing/cond/add/Switch"
  op: "Switch"
  input: "is_non_decreasing/sub"
  input: "is_non_decreasing/cond/pred_id"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@is_non_decreasing/sub"
      }
    }
  }
}
node {
  name: "is_non_decreasing/cond/ones_like/Shape"
  op: "Const"
  input: "^is_non_decreasing/cond/switch_f"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 1
          }
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "is_non_decreasing/cond/ones_like/Const"
  op: "Const"
  input: "^is_non_decreasing/cond/switch_f"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "is_non_decreasing/cond/ones_like"
  op: "Fill"
  input: "is_non_decreasing/cond/ones_like/Shape"
  input: "is_non_decreasing/cond/ones_like/Const"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "index_type"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "is_non_decreasing/cond/StridedSlice/begin"
  op: "Const"
  input: "^is_non_decreasing/cond/switch_f"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 1
          }
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "is_non_decreasing/cond/StridedSlice"
  op: "StridedSlice"
  input: "is_non_decreasing/cond/StridedSlice/Switch"
  input: "is_non_decreasing/cond/StridedSlice/begin"
  input: "is_non_decreasing/cond/add"
  input: "is_non_decreasing/cond/ones_like"
  attr {
    key: "Index"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "begin_mask"
    value {
      i: 0
    }
  }
  attr {
    key: "ellipsis_mask"
    value {
      i: 0
    }
  }
  attr {
    key: "end_mask"
    value {
      i: 0
    }
  }
  attr {
    key: "new_axis_mask"
    value {
      i: 0
    }
  }
  attr {
    key: "shrink_axis_mask"
    value {
      i: 0
    }
  }
}
node {
  name: "is_non_decreasing/cond/StridedSlice/Switch"
  op: "Switch"
  input: "is_non_decreasing/Reshape"
  input: "is_non_decreasing/cond/pred_id"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@is_non_decreasing/Reshape"
      }
    }
  }
}
node {
  name: "is_non_decreasing/cond/ones_like_1/Shape"
  op: "Const"
  input: "^is_non_decreasing/cond/switch_f"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 1
          }
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "is_non_decreasing/cond/ones_like_1/Const"
  op: "Const"
  input: "^is_non_decreasing/cond/switch_f"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "is_non_decreasing/cond/ones_like_1"
  op: "Fill"
  input: "is_non_decreasing/cond/ones_like_1/Shape"
  input: "is_non_decreasing/cond/ones_like_1/Const"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "index_type"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "is_non_decreasing/cond/StridedSlice_1/begin"
  op: "Const"
  input: "^is_non_decreasing/cond/switch_f"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 1
          }
        }
        int_val: 0
      }
    }
  }
}
node {
  name: "is_non_decreasing/cond/StridedSlice_1"
  op: "StridedSlice"
  input: "is_non_decreasing/cond/StridedSlice/Switch"
  input: "is_non_decreasing/cond/StridedSlice_1/begin"
  input: "is_non_decreasing/cond/add/Switch"
  input: "is_non_decreasing/cond/ones_like_1"
  attr {
    key: "Index"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "begin_mask"
    value {
      i: 0
    }
  }
  attr {
    key: "ellipsis_mask"
    value {
      i: 0
    }
  }
  attr {
    key: "end_mask"
    value {
      i: 0
    }
  }
  attr {
    key: "new_axis_mask"
    value {
      i: 0
    }
  }
  attr {
    key: "shrink_axis_mask"
    value {
      i: 0
    }
  }
}
node {
  name: "is_non_decreasing/cond/sub"
  op: "Sub"
  input: "is_non_decreasing/cond/StridedSlice"
  input: "is_non_decreasing/cond/StridedSlice_1"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "is_non_decreasing/cond/Merge"
  op: "Merge"
  input: "is_non_decreasing/cond/sub"
  input: "is_non_decreasing/cond/Const"
  attr {
    key: "N"
    value {
      i: 2
    }
  }
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "is_non_decreasing/Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 0.0
      }
    }
  }
}
node {
  name: "is_non_decreasing/LessEqual"
  op: "LessEqual"
  input: "is_non_decreasing/Const"
  input: "is_non_decreasing/cond/Merge"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "is_non_decreasing/Const_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 1
          }
        }
        int_val: 0
      }
    }
  }
}
node {
  name: "is_non_decreasing/All"
  op: "All"
  input: "is_non_decreasing/LessEqual"
  input: "is_non_decreasing/Const_1"
  attr {
    key: "Tidx"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "keep_dims"
    value {
      b: false
    }
  }
}
library {
}
