node {
  name: "in_0"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_HALF
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_HALF
        tensor_shape {
          dim {
            size: 1
          }
          dim {
            size: 8
          }
          dim {
            size: 8
          }
          dim {
            size: 8
          }
          dim {
            size: 6
          }
        }
        half_val: 14974
        half_val: 13976
        half_val: 11504
        half_val: 14280
        half_val: 14830
        half_val: 14870
        half_val: 12528
        half_val: 14434
        half_val: 14996
        half_val: 13104
        half_val: 7424
        half_val: 14636
        half_val: 13144
        half_val: 15086
        half_val: 14680
        half_val: 13360
        half_val: 15080
        half_val: 14416
        half_val: 15250
        half_val: 14454
        half_val: 14284
        half_val: 13988
        half_val: 13548
        half_val: 15196
        half_val: 13136
        half_val: 15116
        half_val: 14372
        half_val: 12456
        half_val: 10368
        half_val: 14440
        half_val: 14120
        half_val: 13324
        half_val: 7936
        half_val: 15094
        half_val: 13888
        half_val: 12928
        half_val: 9280
        half_val: 14448
        half_val: 14478
        half_val: 15238
        half_val: 13496
        half_val: 14784
        half_val: 11904
        half_val: 15288
        half_val: 14664
        half_val: 14510
        half_val: 15030
        half_val: 13920
        half_val: 13668
        half_val: 11520
        half_val: 13800
        half_val: 14690
        half_val: 12304
        half_val: 9280
        half_val: 9984
        half_val: 13812
        half_val: 14978
        half_val: 14994
        half_val: 11776
        half_val: 15000
        half_val: 14876
        half_val: 12504
        half_val: 13332
        half_val: 13728
        half_val: 10528
        half_val: 14598
        half_val: 14316
        half_val: 15050
        half_val: 12648
        half_val: 7424
        half_val: 14280
        half_val: 12520
        half_val: 14992
        half_val: 15322
        half_val: 14732
        half_val: 15266
        half_val: 14444
        half_val: 15196
        half_val: 14474
        half_val: 10528
        half_val: 14406
        half_val: 13176
        half_val: 13208
        half_val: 15320
        half_val: 14714
        half_val: 14838
        half_val: 14644
        half_val: 15216
        half_val: 15356
        half_val: 13796
        half_val: 14706
        half_val: 14864
        half_val: 15042
        half_val: 14316
        half_val: 14570
        half_val: 14012
        half_val: 12944
        half_val: 14252
        half_val: 14974
        half_val: 11680
        half_val: 13376
        half_val: 12944
        half_val: 12712
        half_val: 15284
        half_val: 14810
        half_val: 13732
        half_val: 13048
        half_val: 10592
        half_val: 14044
        half_val: 13896
        half_val: 13008
        half_val: 14682
        half_val: 14088
        half_val: 14780
        half_val: 12864
        half_val: 14918
        half_val: 13676
        half_val: 13748
        half_val: 14052
        half_val: 12864
        half_val: 14458
        half_val: 14664
        half_val: 15246
        half_val: 14360
        half_val: 13080
        half_val: 13372
        half_val: 14124
        half_val: 14794
        half_val: 14784
        half_val: 13964
        half_val: 13780
        half_val: 15194
        half_val: 15284
        half_val: 14986
        half_val: 15098
        half_val: 15166
        half_val: 13556
        half_val: 12856
        half_val: 15312
        half_val: 13120
        half_val: 15278
        half_val: 14918
        half_val: 13432
        half_val: 14830
        half_val: 15010
        half_val: 14902
        half_val: 11648
        half_val: 13708
        half_val: 14614
        half_val: 14788
        half_val: 14236
        half_val: 13588
        half_val: 15346
        half_val: 13712
        half_val: 10720
        half_val: 15138
        half_val: 15090
        half_val: 15252
        half_val: 14836
        half_val: 11520
        half_val: 14860
        half_val: 15106
        half_val: 12944
        half_val: 13808
        half_val: 14934
        half_val: 13476
        half_val: 14874
        half_val: 15324
        half_val: 15344
        half_val: 11760
        half_val: 15148
        half_val: 13968
        half_val: 7680
        half_val: 13296
        half_val: 14536
        half_val: 14940
        half_val: 15284
        half_val: 14984
        half_val: 14764
        half_val: 14300
        half_val: 15348
        half_val: 12144
        half_val: 15130
        half_val: 11552
        half_val: 15246
        half_val: 15288
        half_val: 14640
        half_val: 15238
        half_val: 14960
        half_val: 13040
        half_val: 15336
        half_val: 15224
        half_val: 13472
        half_val: 13024
        half_val: 13972
        half_val: 14678
        half_val: 13876
        half_val: 14032
        half_val: 14200
        half_val: 14514
        half_val: 14410
        half_val: 11680
        half_val: 14478
        half_val: 13732
        half_val: 14820
        half_val: 15196
        half_val: 14936
        half_val: 14728
        half_val: 14452
        half_val: 14426
        half_val: 14678
        half_val: 13504
        half_val: 12984
        half_val: 14856
        half_val: 13608
        half_val: 15164
        half_val: 12944
        half_val: 13288
        half_val: 14486
        half_val: 15036
        half_val: 13352
        half_val: 15270
        half_val: 13428
        half_val: 13216
        half_val: 14028
        half_val: 15040
        half_val: 14916
        half_val: 13720
        half_val: 12624
        half_val: 12592
        half_val: 14706
        half_val: 14720
        half_val: 13996
        half_val: 15118
        half_val: 15172
        half_val: 13208
        half_val: 11680
        half_val: 14392
        half_val: 12288
        half_val: 14388
        half_val: 10336
        half_val: 14538
        half_val: 14252
        half_val: 10816
        half_val: 10720
        half_val: 13476
        half_val: 11728
        half_val: 15174
        half_val: 12784
        half_val: 14696
        half_val: 15134
        half_val: 13160
        half_val: 13684
        half_val: 15194
        half_val: 14482
        half_val: 13496
        half_val: 14204
        half_val: 10048
        half_val: 13636
        half_val: 13792
        half_val: 12392
        half_val: 14664
        half_val: 15324
        half_val: 12984
        half_val: 13796
        half_val: 12592
        half_val: 12672
        half_val: 13704
        half_val: 14370
        half_val: 13468
        half_val: 14768
        half_val: 14830
        half_val: 14726
        half_val: 11776
        half_val: 11312
        half_val: 14088
        half_val: 14606
        half_val: 13216
        half_val: 12256
        half_val: 13464
        half_val: 14738
        half_val: 14300
        half_val: 14540
        half_val: 14670
        half_val: 14968
        half_val: 0
        half_val: 14088
        half_val: 15010
        half_val: 14618
        half_val: 14180
        half_val: 11840
        half_val: 14980
        half_val: 14772
        half_val: 13452
        half_val: 14802
        half_val: 12320
        half_val: 14522
        half_val: 15110
        half_val: 13364
        half_val: 12552
        half_val: 13040
        half_val: 14646
        half_val: 12192
        half_val: 12096
        half_val: 14678
        half_val: 14718
        half_val: 14900
        half_val: 14912
        half_val: 12720
        half_val: 12728
        half_val: 14714
        half_val: 14518
        half_val: 14560
        half_val: 13692
        half_val: 14968
        half_val: 13776
        half_val: 10336
        half_val: 14528
        half_val: 14060
        half_val: 14348
        half_val: 14986
        half_val: 14686
        half_val: 14562
        half_val: 10720
        half_val: 14340
        half_val: 13756
        half_val: 15170
        half_val: 11664
        half_val: 14960
        half_val: 14748
        half_val: 8960
        half_val: 15260
        half_val: 12768
        half_val: 13320
        half_val: 14728
        half_val: 10176
        half_val: 15124
        half_val: 10592
        half_val: 14244
        half_val: 14990
        half_val: 14996
        half_val: 14716
        half_val: 15162
        half_val: 15036
        half_val: 15062
        half_val: 14124
        half_val: 14852
        half_val: 12336
        half_val: 10592
        half_val: 12464
        half_val: 13436
        half_val: 15162
        half_val: 13944
        half_val: 13464
        half_val: 14164
        half_val: 15212
        half_val: 12928
        half_val: 15348
        half_val: 13736
        half_val: 14622
        half_val: 13432
        half_val: 14722
        half_val: 14544
        half_val: 14592
        half_val: 7680
        half_val: 12928
        half_val: 14622
        half_val: 14132
        half_val: 14734
        half_val: 14562
        half_val: 15288
        half_val: 12656
        half_val: 15108
        half_val: 11856
        half_val: 13480
        half_val: 14402
        half_val: 12552
        half_val: 14404
        half_val: 14652
        half_val: 15210
        half_val: 13968
        half_val: 14568
        half_val: 15096
        half_val: 14370
        half_val: 14578
        half_val: 14738
        half_val: 13996
        half_val: 13752
        half_val: 14854
        half_val: 14480
        half_val: 14664
        half_val: 14592
        half_val: 14494
        half_val: 14938
        half_val: 8192
        half_val: 10976
        half_val: 15184
        half_val: 14240
        half_val: 15268
        half_val: 12192
        half_val: 14658
        half_val: 12864
        half_val: 12512
        half_val: 14854
        half_val: 14096
        half_val: 12144
        half_val: 14762
        half_val: 15170
        half_val: 14762
        half_val: 13960
        half_val: 14956
        half_val: 15324
        half_val: 13960
        half_val: 12992
        half_val: 14296
        half_val: 14784
        half_val: 14800
        half_val: 14698
        half_val: 14704
        half_val: 14068
        half_val: 13948
        half_val: 13680
        half_val: 15144
        half_val: 14708
        half_val: 13216
        half_val: 15224
        half_val: 14140
        half_val: 14974
        half_val: 15154
        half_val: 14986
        half_val: 13912
        half_val: 14342
        half_val: 13896
        half_val: 14976
        half_val: 13704
        half_val: 12488
        half_val: 14470
        half_val: 13616
        half_val: 14522
        half_val: 14664
        half_val: 14634
        half_val: 13492
        half_val: 15350
        half_val: 13880
        half_val: 15334
        half_val: 14188
        half_val: 14810
        half_val: 14568
        half_val: 13800
        half_val: 14668
        half_val: 15258
        half_val: 14496
        half_val: 14942
        half_val: 14736
        half_val: 15094
        half_val: 15120
        half_val: 12520
        half_val: 14916
        half_val: 14738
        half_val: 15116
        half_val: 13732
        half_val: 13336
        half_val: 14650
        half_val: 14898
        half_val: 15236
        half_val: 15170
        half_val: 14946
        half_val: 15248
        half_val: 14560
        half_val: 14760
        half_val: 15268
        half_val: 12176
        half_val: 14966
        half_val: 14092
        half_val: 14680
        half_val: 13272
        half_val: 14132
        half_val: 13160
        half_val: 15038
        half_val: 14740
        half_val: 13356
        half_val: 13728
        half_val: 15236
        half_val: 15202
        half_val: 15106
        half_val: 10752
        half_val: 11312
        half_val: 15330
        half_val: 14896
        half_val: 13384
        half_val: 11872
        half_val: 14044
        half_val: 14758
        half_val: 15302
        half_val: 14580
        half_val: 13432
        half_val: 13056
        half_val: 15260
        half_val: 12272
        half_val: 14902
        half_val: 7936
        half_val: 13780
        half_val: 14636
        half_val: 13192
        half_val: 14820
        half_val: 13360
        half_val: 13672
        half_val: 14564
        half_val: 15068
        half_val: 15182
        half_val: 14520
        half_val: 8576
        half_val: 14526
        half_val: 11040
        half_val: 13520
        half_val: 14552
        half_val: 14510
        half_val: 15298
        half_val: 14348
        half_val: 14586
        half_val: 14348
        half_val: 13932
        half_val: 13248
        half_val: 8320
        half_val: 14774
        half_val: 15048
        half_val: 13520
        half_val: 14742
        half_val: 14672
        half_val: 14832
        half_val: 12584
        half_val: 13892
        half_val: 13776
        half_val: 14164
        half_val: 14664
        half_val: 15308
        half_val: 15108
        half_val: 14964
        half_val: 14600
        half_val: 13200
        half_val: 14810
        half_val: 14748
        half_val: 15184
        half_val: 14212
        half_val: 13624
        half_val: 12656
        half_val: 11232
        half_val: 14060
        half_val: 14726
        half_val: 15254
        half_val: 14414
        half_val: 14436
        half_val: 14692
        half_val: 15282
        half_val: 14236
        half_val: 12680
        half_val: 15166
        half_val: 14488
        half_val: 12416
        half_val: 14912
        half_val: 15002
        half_val: 14702
        half_val: 15012
        half_val: 13136
        half_val: 15136
        half_val: 13984
        half_val: 13312
        half_val: 14734
        half_val: 13608
        half_val: 14212
        half_val: 14928
        half_val: 14382
        half_val: 14076
        half_val: 15346
        half_val: 14412
        half_val: 13780
        half_val: 15132
        half_val: 13980
        half_val: 14428
        half_val: 14112
        half_val: 14048
        half_val: 13112
        half_val: 14648
        half_val: 12648
        half_val: 15204
        half_val: 10368
        half_val: 13476
        half_val: 14502
        half_val: 14358
        half_val: 14864
        half_val: 15292
        half_val: 9344
        half_val: 14760
        half_val: 14512
        half_val: 13876
        half_val: 14316
        half_val: 14996
        half_val: 14798
        half_val: 6656
        half_val: 15052
        half_val: 13200
        half_val: 14336
        half_val: 13748
        half_val: 14972
        half_val: 14946
        half_val: 12808
        half_val: 14474
        half_val: 13800
        half_val: 14734
        half_val: 13980
        half_val: 12520
        half_val: 11760
        half_val: 12656
        half_val: 14502
        half_val: 13672
        half_val: 15198
        half_val: 14658
        half_val: 12000
        half_val: 12128
        half_val: 13344
        half_val: 15030
        half_val: 12432
        half_val: 14984
        half_val: 14450
        half_val: 11104
        half_val: 13732
        half_val: 13736
        half_val: 14508
        half_val: 14424
        half_val: 13988
        half_val: 14192
        half_val: 13476
        half_val: 13808
        half_val: 14908
        half_val: 14604
        half_val: 15330
        half_val: 14890
        half_val: 15124
        half_val: 14554
        half_val: 14380
        half_val: 11376
        half_val: 13652
        half_val: 15190
        half_val: 14572
        half_val: 14796
        half_val: 14676
        half_val: 13412
        half_val: 12304
        half_val: 14772
        half_val: 14974
        half_val: 14376
        half_val: 14818
        half_val: 14422
        half_val: 14426
        half_val: 14044
        half_val: 15116
        half_val: 11776
        half_val: 14510
        half_val: 13536
        half_val: 14350
        half_val: 14252
        half_val: 14628
        half_val: 14544
        half_val: 14044
        half_val: 11072
        half_val: 8576
        half_val: 9344
        half_val: 11904
        half_val: 13956
        half_val: 12032
        half_val: 11632
        half_val: 15094
        half_val: 13660
        half_val: 7936
        half_val: 15308
        half_val: 14436
        half_val: 15136
        half_val: 12568
        half_val: 15190
        half_val: 13684
        half_val: 8832
        half_val: 13880
        half_val: 14782
        half_val: 14692
        half_val: 12464
        half_val: 13796
        half_val: 11808
        half_val: 14836
        half_val: 14874
        half_val: 11776
        half_val: 14148
        half_val: 12632
        half_val: 15126
        half_val: 13232
        half_val: 13948
        half_val: 13784
        half_val: 14320
        half_val: 14500
        half_val: 12000
        half_val: 14564
        half_val: 15286
        half_val: 12776
        half_val: 10944
        half_val: 13684
        half_val: 14356
        half_val: 14044
        half_val: 13892
        half_val: 12160
        half_val: 13576
        half_val: 14936
        half_val: 14024
        half_val: 14560
        half_val: 13208
        half_val: 13688
        half_val: 12904
        half_val: 13016
        half_val: 14406
        half_val: 13120
        half_val: 14762
        half_val: 15350
        half_val: 12512
        half_val: 15312
        half_val: 14608
        half_val: 14814
        half_val: 13620
        half_val: 15030
        half_val: 13688
        half_val: 13404
        half_val: 12656
        half_val: 11264
        half_val: 13324
        half_val: 15338
        half_val: 12808
        half_val: 5120
        half_val: 14584
        half_val: 14612
        half_val: 15138
        half_val: 14396
        half_val: 14436
        half_val: 14478
        half_val: 14934
        half_val: 13288
        half_val: 12528
        half_val: 14478
        half_val: 14776
        half_val: 14522
        half_val: 15340
        half_val: 15294
        half_val: 14016
        half_val: 13496
        half_val: 13844
        half_val: 11808
        half_val: 14772
        half_val: 15100
        half_val: 14770
        half_val: 14354
        half_val: 12776
        half_val: 14220
        half_val: 14812
        half_val: 13200
        half_val: 13088
        half_val: 14916
        half_val: 12888
        half_val: 14810
        half_val: 12384
        half_val: 11264
        half_val: 12832
        half_val: 13656
        half_val: 13104
        half_val: 15144
        half_val: 12360
        half_val: 14192
        half_val: 15214
        half_val: 8576
        half_val: 5120
        half_val: 15034
        half_val: 14430
        half_val: 14504
        half_val: 15178
        half_val: 15194
        half_val: 15112
        half_val: 14536
        half_val: 15164
        half_val: 12272
        half_val: 13332
        half_val: 15096
        half_val: 14978
        half_val: 15266
        half_val: 12296
        half_val: 14422
        half_val: 11616
        half_val: 13908
        half_val: 14984
        half_val: 15284
        half_val: 14092
        half_val: 13816
        half_val: 13940
        half_val: 15200
        half_val: 15064
        half_val: 13856
        half_val: 13452
        half_val: 13332
        half_val: 15002
        half_val: 14680
        half_val: 10048
        half_val: 10464
        half_val: 13384
        half_val: 14376
        half_val: 12896
        half_val: 15272
        half_val: 15354
        half_val: 13808
        half_val: 6656
        half_val: 14668
        half_val: 14656
        half_val: 13436
        half_val: 14304
        half_val: 15258
        half_val: 15132
        half_val: 13496
        half_val: 14260
        half_val: 14806
        half_val: 14858
        half_val: 14588
        half_val: 14368
        half_val: 14944
        half_val: 15260
        half_val: 15354
        half_val: 14380
        half_val: 14308
        half_val: 13008
        half_val: 13740
        half_val: 14578
        half_val: 13988
        half_val: 11872
        half_val: 13816
        half_val: 14618
        half_val: 14814
        half_val: 14802
        half_val: 13536
        half_val: 12464
        half_val: 14826
        half_val: 14866
        half_val: 12440
        half_val: 12496
        half_val: 14484
        half_val: 13280
        half_val: 14752
        half_val: 11008
        half_val: 15180
        half_val: 14716
        half_val: 13544
        half_val: 13216
        half_val: 15252
        half_val: 14692
        half_val: 14420
        half_val: 14376
        half_val: 11696
        half_val: 13972
        half_val: 15194
        half_val: 14960
        half_val: 14568
        half_val: 12432
        half_val: 13668
        half_val: 13128
        half_val: 15192
        half_val: 14642
        half_val: 14520
        half_val: 13756
        half_val: 12664
        half_val: 11600
        half_val: 14848
        half_val: 14904
        half_val: 15290
        half_val: 14760
        half_val: 11552
        half_val: 11616
        half_val: 14792
        half_val: 14628
        half_val: 15108
        half_val: 12440
        half_val: 14360
        half_val: 14926
        half_val: 15018
        half_val: 12144
        half_val: 13492
        half_val: 13792
        half_val: 10592
        half_val: 14910
        half_val: 14954
        half_val: 13492
        half_val: 13588
        half_val: 11200
        half_val: 15238
        half_val: 8960
        half_val: 15088
        half_val: 13112
        half_val: 14598
        half_val: 14418
        half_val: 13160
        half_val: 15018
        half_val: 15108
        half_val: 14838
        half_val: 14748
        half_val: 14490
        half_val: 13216
        half_val: 14240
        half_val: 11664
        half_val: 14616
        half_val: 14534
        half_val: 13764
        half_val: 12296
        half_val: 13088
        half_val: 15340
        half_val: 13528
        half_val: 11280
        half_val: 15270
        half_val: 14756
        half_val: 14442
        half_val: 14228
        half_val: 15240
        half_val: 13348
        half_val: 13588
        half_val: 14896
        half_val: 14566
        half_val: 14456
        half_val: 10688
        half_val: 10816
        half_val: 11568
        half_val: 14782
        half_val: 12920
        half_val: 14500
        half_val: 13768
        half_val: 15214
        half_val: 13748
        half_val: 14784
        half_val: 14608
        half_val: 11568
        half_val: 15158
        half_val: 15082
        half_val: 13560
        half_val: 12720
        half_val: 13904
        half_val: 14036
        half_val: 15082
        half_val: 13720
        half_val: 15288
        half_val: 12576
        half_val: 11600
        half_val: 14724
        half_val: 15084
        half_val: 14832
        half_val: 13552
        half_val: 12784
        half_val: 7424
        half_val: 14706
        half_val: 14856
        half_val: 14514
        half_val: 13272
        half_val: 11360
        half_val: 14958
        half_val: 12824
        half_val: 12424
        half_val: 7680
        half_val: 13692
        half_val: 15290
        half_val: 14382
        half_val: 12568
        half_val: 14744
        half_val: 14842
        half_val: 13484
        half_val: 14526
        half_val: 11456
        half_val: 14714
        half_val: 14660
        half_val: 15196
        half_val: 14172
        half_val: 10784
        half_val: 14754
        half_val: 13984
        half_val: 12640
        half_val: 14570
        half_val: 11808
        half_val: 9792
        half_val: 13016
        half_val: 13408
        half_val: 12592
        half_val: 13064
        half_val: 15238
        half_val: 14996
        half_val: 14510
        half_val: 11616
        half_val: 13216
        half_val: 12864
        half_val: 14376
        half_val: 11984
        half_val: 14268
        half_val: 12448
        half_val: 13504
        half_val: 11008
        half_val: 13544
        half_val: 15254
        half_val: 13412
        half_val: 13356
        half_val: 14856
        half_val: 15106
        half_val: 14642
        half_val: 15206
        half_val: 12112
        half_val: 12496
        half_val: 15196
        half_val: 15044
        half_val: 15044
        half_val: 11888
        half_val: 15012
        half_val: 12376
        half_val: 14172
        half_val: 15090
        half_val: 14364
        half_val: 13120
        half_val: 9856
        half_val: 11392
        half_val: 14792
        half_val: 14602
        half_val: 15132
        half_val: 14902
        half_val: 14056
        half_val: 13824
        half_val: 14570
        half_val: 12728
        half_val: 14524
        half_val: 12336
        half_val: 11488
        half_val: 13368
        half_val: 15302
        half_val: 13896
        half_val: 13456
        half_val: 13684
        half_val: 14212
        half_val: 12392
        half_val: 15160
        half_val: 14392
        half_val: 14666
        half_val: 14672
        half_val: 5120
        half_val: 13952
        half_val: 13732
        half_val: 15076
        half_val: 13728
        half_val: 14434
        half_val: 12728
        half_val: 13408
        half_val: 14548
        half_val: 12456
        half_val: 12480
        half_val: 14438
        half_val: 14764
        half_val: 13168
        half_val: 13900
        half_val: 12128
        half_val: 11328
        half_val: 14908
        half_val: 15158
        half_val: 14514
        half_val: 10432
        half_val: 11264
        half_val: 15204
        half_val: 15330
        half_val: 15298
        half_val: 13716
        half_val: 13940
        half_val: 14384
        half_val: 14918
        half_val: 14410
        half_val: 14340
        half_val: 12544
        half_val: 7424
        half_val: 9408
        half_val: 15276
        half_val: 14884
        half_val: 12816
        half_val: 15234
        half_val: 14758
        half_val: 13660
        half_val: 15342
        half_val: 14718
        half_val: 14540
        half_val: 14770
        half_val: 11632
        half_val: 10272
        half_val: 14156
        half_val: 12208
        half_val: 14614
        half_val: 13736
        half_val: 15004
        half_val: 12632
        half_val: 13636
        half_val: 13208
        half_val: 14706
        half_val: 14180
        half_val: 14802
        half_val: 14540
        half_val: 14056
        half_val: 14828
        half_val: 13552
        half_val: 14372
        half_val: 10304
        half_val: 15056
        half_val: 14172
        half_val: 14340
        half_val: 14430
        half_val: 15332
        half_val: 14776
        half_val: 14712
        half_val: 11040
        half_val: 13784
        half_val: 15340
        half_val: 14584
        half_val: 13804
        half_val: 14600
        half_val: 15242
        half_val: 12744
        half_val: 13664
        half_val: 14656
        half_val: 12704
        half_val: 13884
        half_val: 15330
        half_val: 13184
        half_val: 14388
        half_val: 11200
        half_val: 15162
        half_val: 11744
        half_val: 11760
        half_val: 15058
        half_val: 13708
        half_val: 10752
        half_val: 15288
        half_val: 15334
        half_val: 13580
        half_val: 9984
        half_val: 15082
        half_val: 14160
        half_val: 15324
        half_val: 9280
        half_val: 14606
        half_val: 14256
        half_val: 15226
        half_val: 14774
        half_val: 14760
        half_val: 14682
        half_val: 14730
        half_val: 13752
        half_val: 10176
        half_val: 14636
        half_val: 15218
        half_val: 13496
        half_val: 15216
        half_val: 13184
        half_val: 13456
        half_val: 13112
        half_val: 13996
        half_val: 14738
        half_val: 14488
        half_val: 14804
        half_val: 14288
        half_val: 13416
        half_val: 12368
        half_val: 12320
        half_val: 13980
        half_val: 14804
        half_val: 13536
        half_val: 14440
        half_val: 14028
        half_val: 14682
        half_val: 13404
        half_val: 14664
        half_val: 14236
        half_val: 13684
        half_val: 15114
        half_val: 14484
        half_val: 13460
        half_val: 14726
        half_val: 12776
        half_val: 14004
        half_val: 14332
        half_val: 11312
        half_val: 15016
        half_val: 14980
        half_val: 14200
        half_val: 14370
        half_val: 14774
        half_val: 15066
        half_val: 13788
        half_val: 13788
        half_val: 10976
        half_val: 9216
        half_val: 13200
        half_val: 13748
        half_val: 13976
        half_val: 10048
        half_val: 13372
        half_val: 14866
        half_val: 14534
        half_val: 13344
        half_val: 14810
        half_val: 14864
        half_val: 12936
        half_val: 14876
        half_val: 14876
        half_val: 14344
        half_val: 15160
        half_val: 14160
        half_val: 14388
        half_val: 14650
        half_val: 14840
        half_val: 12560
        half_val: 14686
        half_val: 13544
        half_val: 13504
        half_val: 13956
        half_val: 15248
        half_val: 14788
        half_val: 14770
        half_val: 14368
        half_val: 14424
        half_val: 13768
        half_val: 13448
        half_val: 14152
        half_val: 13972
        half_val: 14838
        half_val: 15010
        half_val: 12648
        half_val: 14510
        half_val: 14628
        half_val: 14588
        half_val: 15270
        half_val: 14492
        half_val: 13448
        half_val: 13948
        half_val: 12296
        half_val: 14794
        half_val: 15068
        half_val: 14764
        half_val: 14992
        half_val: 11616
        half_val: 12960
        half_val: 14630
        half_val: 12032
        half_val: 14420
        half_val: 10976
        half_val: 13620
        half_val: 13576
        half_val: 14462
        half_val: 12632
        half_val: 14358
        half_val: 12752
        half_val: 9344
        half_val: 12600
        half_val: 14758
        half_val: 12824
        half_val: 14894
        half_val: 12360
        half_val: 13724
        half_val: 13404
        half_val: 11712
        half_val: 10400
        half_val: 14518
        half_val: 14626
        half_val: 14378
        half_val: 12424
        half_val: 12584
        half_val: 15334
        half_val: 15216
        half_val: 14804
        half_val: 15128
        half_val: 14730
        half_val: 13264
        half_val: 13516
        half_val: 12448
        half_val: 15020
        half_val: 14614
        half_val: 14518
        half_val: 14596
        half_val: 7424
        half_val: 13716
        half_val: 13520
        half_val: 14486
        half_val: 15016
        half_val: 14728
        half_val: 13456
        half_val: 15252
        half_val: 13388
        half_val: 12712
        half_val: 13032
        half_val: 14272
        half_val: 15146
        half_val: 14814
        half_val: 14660
        half_val: 13928
        half_val: 7936
        half_val: 14396
        half_val: 14672
        half_val: 15138
        half_val: 14168
        half_val: 14688
        half_val: 15356
        half_val: 15338
        half_val: 14694
        half_val: 14296
        half_val: 14594
        half_val: 13248
        half_val: 13232
        half_val: 13904
        half_val: 14468
        half_val: 15014
        half_val: 15324
        half_val: 11856
        half_val: 14036
        half_val: 13324
        half_val: 15162
        half_val: 13388
        half_val: 13256
        half_val: 14828
        half_val: 14834
        half_val: 13456
        half_val: 13368
        half_val: 14852
        half_val: 14604
        half_val: 14574
        half_val: 13876
        half_val: 14904
        half_val: 14454
        half_val: 12128
        half_val: 12960
        half_val: 14400
        half_val: 14556
        half_val: 14012
        half_val: 12424
        half_val: 14562
        half_val: 12648
        half_val: 11136
        half_val: 14610
        half_val: 12744
        half_val: 14724
        half_val: 14924
        half_val: 14430
        half_val: 14394
        half_val: 14380
        half_val: 14866
        half_val: 14512
        half_val: 12944
        half_val: 15110
        half_val: 13952
        half_val: 15240
        half_val: 15266
        half_val: 14642
        half_val: 11584
        half_val: 14920
        half_val: 12312
        half_val: 14100
        half_val: 13904
        half_val: 15058
        half_val: 11568
        half_val: 14540
        half_val: 13160
        half_val: 13224
        half_val: 13256
        half_val: 14496
        half_val: 12080
        half_val: 15254
        half_val: 15198
        half_val: 15248
        half_val: 14728
        half_val: 13684
        half_val: 14726
        half_val: 12320
        half_val: 14388
        half_val: 9408
        half_val: 13024
        half_val: 14348
        half_val: 14682
        half_val: 14726
        half_val: 12792
        half_val: 9664
        half_val: 14570
        half_val: 15234
        half_val: 14320
        half_val: 14008
        half_val: 15208
        half_val: 6144
        half_val: 13332
        half_val: 11440
        half_val: 14660
        half_val: 14608
        half_val: 12992
        half_val: 14822
        half_val: 14402
        half_val: 14354
        half_val: 13288
        half_val: 12608
        half_val: 15080
        half_val: 11600
        half_val: 14316
        half_val: 10976
        half_val: 11952
        half_val: 15084
        half_val: 15082
        half_val: 15276
        half_val: 14970
        half_val: 13972
        half_val: 13848
        half_val: 12112
        half_val: 14788
        half_val: 14552
        half_val: 13160
        half_val: 13008
        half_val: 13976
        half_val: 11568
        half_val: 15168
        half_val: 14140
        half_val: 14588
        half_val: 14530
        half_val: 14500
        half_val: 12728
        half_val: 13744
        half_val: 14730
        half_val: 13112
        half_val: 14336
        half_val: 15280
        half_val: 15132
        half_val: 13716
        half_val: 14710
        half_val: 12112
        half_val: 11952
        half_val: 15340
        half_val: 14820
        half_val: 12560
        half_val: 14204
        half_val: 13480
        half_val: 15148
        half_val: 13616
        half_val: 6144
        half_val: 14244
        half_val: 13912
        half_val: 12440
        half_val: 12616
        half_val: 11760
        half_val: 14364
        half_val: 13152
        half_val: 14512
        half_val: 14556
        half_val: 14542
        half_val: 14702
        half_val: 13940
        half_val: 14616
        half_val: 13748
        half_val: 10784
        half_val: 12520
        half_val: 11664
        half_val: 11424
        half_val: 14350
        half_val: 13176
        half_val: 10752
        half_val: 15292
        half_val: 14560
        half_val: 14914
        half_val: 11520
        half_val: 15030
        half_val: 14472
        half_val: 9344
        half_val: 12992
        half_val: 14008
        half_val: 14982
        half_val: 12912
        half_val: 15278
        half_val: 14382
        half_val: 10656
        half_val: 15248
        half_val: 9856
        half_val: 13316
        half_val: 14350
        half_val: 11472
        half_val: 13032
        half_val: 13848
        half_val: 15292
        half_val: 5120
        half_val: 13932
        half_val: 15250
        half_val: 13176
        half_val: 9216
        half_val: 11424
        half_val: 11136
        half_val: 15254
        half_val: 11648
        half_val: 14712
        half_val: 14272
        half_val: 15054
        half_val: 13572
        half_val: 10176
        half_val: 13680
        half_val: 14672
        half_val: 13332
        half_val: 14382
        half_val: 14752
        half_val: 14628
        half_val: 13720
        half_val: 12192
        half_val: 14336
        half_val: 13948
        half_val: 14578
        half_val: 14424
        half_val: 13812
        half_val: 12808
        half_val: 14612
        half_val: 13588
        half_val: 13688
        half_val: 13692
        half_val: 9088
        half_val: 11264
        half_val: 14990
        half_val: 15196
        half_val: 11376
        half_val: 14966
        half_val: 14758
        half_val: 14000
        half_val: 14864
        half_val: 15158
        half_val: 12456
        half_val: 12936
        half_val: 14740
        half_val: 14228
        half_val: 13528
        half_val: 13632
        half_val: 12000
        half_val: 14264
        half_val: 14152
        half_val: 13900
        half_val: 13836
        half_val: 13104
        half_val: 13448
        half_val: 14918
        half_val: 15008
        half_val: 13708
        half_val: 13264
        half_val: 13860
        half_val: 15088
        half_val: 14048
        half_val: 13940
        half_val: 14398
        half_val: 14364
        half_val: 14630
        half_val: 14464
        half_val: 14336
        half_val: 15232
        half_val: 14372
        half_val: 15050
        half_val: 14426
        half_val: 14228
        half_val: 15060
        half_val: 13844
        half_val: 13784
        half_val: 13548
        half_val: 14798
        half_val: 14494
        half_val: 13708
        half_val: 14724
        half_val: 14068
        half_val: 13216
        half_val: 14372
        half_val: 15272
        half_val: 11520
        half_val: 14120
        half_val: 14742
        half_val: 14414
        half_val: 15228
        half_val: 14770
        half_val: 14240
        half_val: 13468
        half_val: 14518
        half_val: 14536
        half_val: 12344
        half_val: 14786
        half_val: 14052
        half_val: 14982
        half_val: 15240
        half_val: 11264
        half_val: 11664
        half_val: 14896
        half_val: 13296
        half_val: 14492
        half_val: 14768
        half_val: 12840
        half_val: 15114
        half_val: 15198
        half_val: 14488
        half_val: 15300
        half_val: 14700
        half_val: 13788
        half_val: 14530
        half_val: 14658
        half_val: 13356
        half_val: 13064
        half_val: 13512
        half_val: 13332
        half_val: 13224
        half_val: 14496
        half_val: 14846
        half_val: 14788
        half_val: 14614
        half_val: 12920
        half_val: 14830
        half_val: 11168
        half_val: 13816
        half_val: 11136
        half_val: 14204
        half_val: 15000
        half_val: 11936
        half_val: 12600
        half_val: 15270
        half_val: 14466
        half_val: 14988
        half_val: 13592
        half_val: 14980
        half_val: 14552
        half_val: 14938
        half_val: 9536
        half_val: 14484
        half_val: 10688
        half_val: 14818
        half_val: 13648
        half_val: 11744
        half_val: 10976
        half_val: 12480
        half_val: 12784
        half_val: 13008
        half_val: 12608
        half_val: 14916
        half_val: 15008
        half_val: 13048
        half_val: 14216
        half_val: 13336
        half_val: 14784
        half_val: 14354
        half_val: 10624
        half_val: 13420
        half_val: 13836
        half_val: 14792
        half_val: 12376
        half_val: 7424
        half_val: 12048
        half_val: 13216
        half_val: 15108
        half_val: 12224
        half_val: 14904
        half_val: 12144
        half_val: 14456
        half_val: 13080
        half_val: 14474
        half_val: 14526
        half_val: 15162
        half_val: 14600
        half_val: 13496
        half_val: 14714
        half_val: 14668
        half_val: 15162
        half_val: 14456
        half_val: 14362
        half_val: 14692
        half_val: 13608
        half_val: 14312
        half_val: 14626
        half_val: 14948
        half_val: 11472
        half_val: 13008
        half_val: 14668
        half_val: 13544
        half_val: 14012
        half_val: 14108
        half_val: 15238
        half_val: 13064
        half_val: 15300
        half_val: 15260
        half_val: 9472
        half_val: 14898
        half_val: 15064
        half_val: 13604
        half_val: 14546
        half_val: 11360
        half_val: 11856
        half_val: 14934
        half_val: 15220
        half_val: 14344
        half_val: 13988
        half_val: 13944
        half_val: 14714
        half_val: 14744
        half_val: 15316
        half_val: 13712
        half_val: 14486
        half_val: 14064
        half_val: 13820
        half_val: 12672
        half_val: 14384
        half_val: 12296
        half_val: 12328
        half_val: 13528
        half_val: 15090
        half_val: 15346
        half_val: 13928
        half_val: 14152
        half_val: 14682
        half_val: 12368
        half_val: 15292
        half_val: 14898
        half_val: 13664
        half_val: 13072
        half_val: 15338
        half_val: 14978
        half_val: 12680
        half_val: 14276
        half_val: 9792
        half_val: 15240
        half_val: 15008
        half_val: 14820
        half_val: 14386
        half_val: 15304
        half_val: 12608
        half_val: 13216
        half_val: 14602
        half_val: 15276
        half_val: 10656
        half_val: 14692
        half_val: 13352
        half_val: 11584
        half_val: 10880
        half_val: 14734
        half_val: 13440
        half_val: 14192
        half_val: 14052
        half_val: 12128
        half_val: 14580
        half_val: 15340
        half_val: 10336
        half_val: 12704
        half_val: 14954
        half_val: 14690
        half_val: 14680
        half_val: 14874
        half_val: 15024
        half_val: 13572
        half_val: 14586
        half_val: 13768
        half_val: 15290
        half_val: 11856
        half_val: 14830
        half_val: 11344
        half_val: 15314
        half_val: 14536
        half_val: 15082
        half_val: 13956
        half_val: 12544
        half_val: 13436
        half_val: 10816
        half_val: 13580
        half_val: 14946
        half_val: 15320
        half_val: 14180
        half_val: 14830
        half_val: 14494
        half_val: 15034
        half_val: 13184
        half_val: 14388
        half_val: 12512
        half_val: 14486
        half_val: 14960
        half_val: 12784
        half_val: 14236
        half_val: 15174
        half_val: 13804
        half_val: 15198
        half_val: 14928
        half_val: 14682
        half_val: 13404
        half_val: 13540
        half_val: 9472
        half_val: 15022
        half_val: 13412
        half_val: 13864
        half_val: 13636
        half_val: 14696
        half_val: 14812
        half_val: 8192
        half_val: 14482
        half_val: 14996
        half_val: 14464
        half_val: 14562
        half_val: 15128
        half_val: 5120
        half_val: 14716
        half_val: 15060
        half_val: 14864
        half_val: 15132
        half_val: 14524
        half_val: 14928
        half_val: 13668
        half_val: 14946
        half_val: 14496
        half_val: 15278
        half_val: 12912
        half_val: 15298
        half_val: 12320
        half_val: 10368
        half_val: 8320
        half_val: 12936
        half_val: 12672
        half_val: 15182
        half_val: 15298
        half_val: 13632
        half_val: 14546
        half_val: 14256
        half_val: 12504
        half_val: 14994
        half_val: 15244
        half_val: 14866
        half_val: 15084
        half_val: 14020
        half_val: 11312
        half_val: 15034
        half_val: 14882
        half_val: 15310
        half_val: 11616
        half_val: 14180
        half_val: 11680
        half_val: 15060
        half_val: 13812
        half_val: 14852
        half_val: 12632
        half_val: 15052
        half_val: 14424
        half_val: 12672
        half_val: 12680
        half_val: 12800
        half_val: 13564
        half_val: 14508
        half_val: 10976
        half_val: 13336
        half_val: 12896
        half_val: 14848
        half_val: 14502
        half_val: 13216
        half_val: 15278
        half_val: 14554
        half_val: 13024
        half_val: 12880
        half_val: 13600
        half_val: 14896
        half_val: 13248
        half_val: 11664
        half_val: 12728
        half_val: 14530
        half_val: 13856
        half_val: 11904
        half_val: 14846
        half_val: 13348
        half_val: 14626
        half_val: 15154
        half_val: 15308
        half_val: 13848
        half_val: 14710
        half_val: 12512
        half_val: 12512
        half_val: 14364
        half_val: 14394
        half_val: 14396
        half_val: 12608
        half_val: 12400
        half_val: 14712
        half_val: 14920
        half_val: 15074
        half_val: 13684
        half_val: 14724
        half_val: 14080
        half_val: 15352
        half_val: 15188
        half_val: 15266
        half_val: 13388
        half_val: 11984
        half_val: 14684
        half_val: 14470
        half_val: 14588
        half_val: 15216
        half_val: 13756
        half_val: 15230
        half_val: 13984
        half_val: 13972
        half_val: 14176
        half_val: 10400
        half_val: 14400
        half_val: 14842
        half_val: 14192
        half_val: 14016
        half_val: 12872
        half_val: 15202
        half_val: 12816
        half_val: 14380
        half_val: 14418
        half_val: 15256
        half_val: 15310
        half_val: 12496
        half_val: 13708
        half_val: 15026
        half_val: 14398
        half_val: 13944
        half_val: 11808
        half_val: 12408
        half_val: 14612
        half_val: 14598
        half_val: 14140
        half_val: 13984
        half_val: 11680
        half_val: 15002
        half_val: 13192
        half_val: 14532
        half_val: 13996
        half_val: 14914
        half_val: 12016
        half_val: 12944
        half_val: 11408
        half_val: 13136
        half_val: 13420
        half_val: 13312
        half_val: 12256
        half_val: 12880
        half_val: 14922
        half_val: 13356
        half_val: 15204
        half_val: 15050
        half_val: 14364
        half_val: 14424
        half_val: 15258
        half_val: 15072
        half_val: 15122
        half_val: 14394
        half_val: 13860
        half_val: 14498
        half_val: 15290
        half_val: 15292
        half_val: 15098
        half_val: 14236
        half_val: 14398
        half_val: 11600
        half_val: 11984
        half_val: 13008
        half_val: 14340
        half_val: 10976
        half_val: 12824
        half_val: 14336
        half_val: 12504
        half_val: 14788
        half_val: 13584
        half_val: 13988
        half_val: 15328
        half_val: 13016
        half_val: 15016
        half_val: 14348
        half_val: 13216
        half_val: 10656
        half_val: 15144
        half_val: 13192
        half_val: 13836
        half_val: 13264
        half_val: 10624
        half_val: 15318
        half_val: 14822
        half_val: 12128
        half_val: 14748
        half_val: 13700
        half_val: 12544
        half_val: 8192
        half_val: 12304
        half_val: 14802
        half_val: 14500
        half_val: 14724
        half_val: 15020
        half_val: 11888
        half_val: 14360
        half_val: 13200
        half_val: 13980
        half_val: 14364
        half_val: 14682
        half_val: 14504
        half_val: 11904
        half_val: 15054
        half_val: 12064
        half_val: 14356
        half_val: 15112
        half_val: 14714
        half_val: 13612
        half_val: 13040
        half_val: 14868
        half_val: 14764
        half_val: 15262
        half_val: 8960
        half_val: 14328
        half_val: 15318
        half_val: 13580
        half_val: 11792
        half_val: 13908
        half_val: 14898
        half_val: 10944
        half_val: 13784
        half_val: 15216
        half_val: 10656
        half_val: 15080
        half_val: 14610
        half_val: 12896
        half_val: 15046
        half_val: 12960
        half_val: 14764
        half_val: 15140
        half_val: 12752
        half_val: 14900
        half_val: 15208
        half_val: 13796
        half_val: 12640
        half_val: 15084
        half_val: 15108
        half_val: 14590
        half_val: 14456
        half_val: 12440
        half_val: 13708
        half_val: 13800
        half_val: 13944
        half_val: 14806
        half_val: 14080
        half_val: 12272
        half_val: 15052
        half_val: 13096
        half_val: 11808
        half_val: 14568
        half_val: 14450
        half_val: 14572
        half_val: 14600
        half_val: 9792
        half_val: 14698
        half_val: 15128
        half_val: 13768
        half_val: 13748
        half_val: 12688
        half_val: 12624
        half_val: 15062
        half_val: 15324
        half_val: 10880
        half_val: 15120
        half_val: 10048
        half_val: 13096
        half_val: 14802
        half_val: 14140
        half_val: 15176
        half_val: 14868
        half_val: 14894
        half_val: 13224
        half_val: 13924
        half_val: 11648
        half_val: 13256
        half_val: 13836
        half_val: 13668
        half_val: 14044
        half_val: 13096
        half_val: 14662
        half_val: 14424
        half_val: 14948
        half_val: 14764
        half_val: 14726
        half_val: 11344
        half_val: 12320
        half_val: 15210
        half_val: 14890
        half_val: 14680
        half_val: 9856
        half_val: 14480
        half_val: 14986
        half_val: 12064
        half_val: 13960
        half_val: 15122
        half_val: 15326
        half_val: 12896
        half_val: 14056
        half_val: 14482
        half_val: 13752
        half_val: 14910
        half_val: 14156
        half_val: 15326
        half_val: 13684
        half_val: 15040
        half_val: 14600
        half_val: 14534
        half_val: 14308
        half_val: 14690
        half_val: 12488
        half_val: 12752
        half_val: 14688
        half_val: 13144
        half_val: 12648
        half_val: 13960
        half_val: 12752
        half_val: 12536
        half_val: 14346
        half_val: 14746
        half_val: 15052
        half_val: 14516
        half_val: 13884
        half_val: 14460
        half_val: 13552
        half_val: 14300
        half_val: 14434
        half_val: 14764
        half_val: 13744
        half_val: 8576
        half_val: 12760
        half_val: 13016
        half_val: 14474
        half_val: 14156
        half_val: 14828
        half_val: 14926
        half_val: 14690
        half_val: 13584
        half_val: 14368
        half_val: 14316
        half_val: 14918
        half_val: 13568
        half_val: 12472
        half_val: 13752
        half_val: 14324
        half_val: 14536
        half_val: 15046
        half_val: 15326
        half_val: 13600
        half_val: 11728
        half_val: 15160
        half_val: 15040
        half_val: 15226
        half_val: 13008
        half_val: 15120
        half_val: 13056
        half_val: 14576
        half_val: 12160
        half_val: 12928
        half_val: 13304
        half_val: 12720
        half_val: 14930
        half_val: 14356
        half_val: 14976
        half_val: 11984
        half_val: 13816
        half_val: 12208
        half_val: 13524
        half_val: 11424
        half_val: 12680
        half_val: 14680
        half_val: 12416
        half_val: 13588
        half_val: 12440
        half_val: 15302
        half_val: 14356
        half_val: 13016
        half_val: 14524
        half_val: 15356
        half_val: 14460
        half_val: 14236
        half_val: 14196
        half_val: 14192
        half_val: 13412
        half_val: 13472
        half_val: 14152
        half_val: 15054
        half_val: 12864
        half_val: 14716
        half_val: 14420
        half_val: 14176
        half_val: 7680
        half_val: 12928
        half_val: 13508
        half_val: 12608
        half_val: 13784
        half_val: 13428
        half_val: 14658
        half_val: 14814
        half_val: 13628
        half_val: 9216
        half_val: 15356
        half_val: 14598
        half_val: 13348
        half_val: 12016
        half_val: 14890
        half_val: 13008
        half_val: 14366
        half_val: 15222
        half_val: 9728
        half_val: 12080
        half_val: 13580
        half_val: 14998
        half_val: 13056
        half_val: 14376
        half_val: 13892
        half_val: 11472
        half_val: 7168
        half_val: 13820
        half_val: 10592
        half_val: 13748
        half_val: 14652
        half_val: 14814
        half_val: 14568
        half_val: 13312
        half_val: 13544
        half_val: 13800
        half_val: 13408
        half_val: 14332
        half_val: 14678
        half_val: 14946
        half_val: 11312
        half_val: 13024
        half_val: 14576
        half_val: 14538
        half_val: 15048
        half_val: 15094
        half_val: 14806
        half_val: 13328
        half_val: 14524
        half_val: 11552
        half_val: 14448
        half_val: 13480
        half_val: 14430
        half_val: 13940
        half_val: 14928
        half_val: 14428
        half_val: 14954
        half_val: 14984
        half_val: 14836
        half_val: 14256
        half_val: 14618
        half_val: 14568
        half_val: 14890
        half_val: 10176
        half_val: 14960
        half_val: 13304
        half_val: 15138
        half_val: 14848
        half_val: 15168
        half_val: 12872
        half_val: 14364
        half_val: 15066
        half_val: 13860
        half_val: 13032
        half_val: 12760
        half_val: 10592
        half_val: 14744
        half_val: 15064
        half_val: 14572
        half_val: 11472
        half_val: 14958
        half_val: 15334
        half_val: 14650
        half_val: 13336
        half_val: 14454
        half_val: 14522
        half_val: 9216
        half_val: 14996
        half_val: 14938
        half_val: 12864
        half_val: 15150
        half_val: 14966
        half_val: 13960
        half_val: 13560
        half_val: 14804
        half_val: 14168
        half_val: 14406
        half_val: 11488
        half_val: 14586
        half_val: 13176
        half_val: 15094
        half_val: 15198
        half_val: 13312
        half_val: 11968
        half_val: 14578
        half_val: 14816
        half_val: 14846
        half_val: 14020
        half_val: 15018
        half_val: 13992
        half_val: 10336
        half_val: 12712
        half_val: 14702
        half_val: 12720
        half_val: 13764
        half_val: 14962
        half_val: 13740
        half_val: 13828
        half_val: 8448
        half_val: 14882
        half_val: 14592
        half_val: 12600
        half_val: 11760
        half_val: 14810
        half_val: 15358
        half_val: 15226
        half_val: 14374
        half_val: 14764
        half_val: 14668
        half_val: 15008
        half_val: 14584
        half_val: 12880
        half_val: 14500
        half_val: 14850
        half_val: 13752
        half_val: 14726
        half_val: 14778
        half_val: 12032
        half_val: 14426
        half_val: 13612
        half_val: 12368
        half_val: 15138
        half_val: 12848
        half_val: 13364
        half_val: 15216
        half_val: 12816
        half_val: 15014
        half_val: 14438
        half_val: 14936
        half_val: 12936
        half_val: 15074
        half_val: 14468
        half_val: 9472
        half_val: 13608
        half_val: 14732
        half_val: 15346
        half_val: 12080
        half_val: 14972
        half_val: 14954
        half_val: 15232
        half_val: 14822
        half_val: 14662
        half_val: 8448
        half_val: 15270
        half_val: 11856
        half_val: 14568
        half_val: 14896
        half_val: 10880
        half_val: 14946
        half_val: 12856
        half_val: 13424
        half_val: 13144
        half_val: 15134
        half_val: 13688
        half_val: 14608
        half_val: 15326
        half_val: 14614
        half_val: 15206
        half_val: 12288
        half_val: 13200
        half_val: 15244
        half_val: 12496
        half_val: 14048
        half_val: 13408
        half_val: 12744
        half_val: 13652
        half_val: 15096
        half_val: 13208
        half_val: 14768
        half_val: 12960
        half_val: 9536
        half_val: 12992
        half_val: 12912
        half_val: 14710
        half_val: 14024
        half_val: 14986
        half_val: 13824
        half_val: 14412
        half_val: 14646
        half_val: 14044
        half_val: 14700
        half_val: 15160
        half_val: 14462
        half_val: 13328
        half_val: 13936
        half_val: 13992
        half_val: 14744
        half_val: 13964
        half_val: 15102
        half_val: 12504
        half_val: 14450
        half_val: 11472
        half_val: 13808
        half_val: 14200
        half_val: 14670
        half_val: 14548
        half_val: 15344
        half_val: 13648
        half_val: 14574
        half_val: 13712
        half_val: 13408
        half_val: 12656
        half_val: 14820
        half_val: 15092
        half_val: 13376
        half_val: 14930
        half_val: 12576
        half_val: 13448
        half_val: 12416
        half_val: 15052
        half_val: 12624
        half_val: 12712
        half_val: 13048
        half_val: 14412
        half_val: 11168
        half_val: 14678
        half_val: 12480
        half_val: 14554
        half_val: 15046
        half_val: 7424
        half_val: 11344
        half_val: 14936
        half_val: 14938
        half_val: 14878
        half_val: 12832
        half_val: 12808
        half_val: 15350
        half_val: 14654
        half_val: 15248
        half_val: 13876
        half_val: 12984
        half_val: 15058
        half_val: 14932
        half_val: 14048
        half_val: 12128
        half_val: 14810
        half_val: 15208
        half_val: 14866
        half_val: 13444
        half_val: 14864
        half_val: 13152
        half_val: 14368
        half_val: 12128
        half_val: 11376
        half_val: 15130
        half_val: 14818
        half_val: 14684
        half_val: 13072
        half_val: 14806
        half_val: 11072
        half_val: 14498
        half_val: 12776
        half_val: 11936
        half_val: 14642
        half_val: 14364
        half_val: 14000
        half_val: 14700
        half_val: 14112
        half_val: 14736
        half_val: 15262
        half_val: 13448
        half_val: 14990
        half_val: 14844
        half_val: 12864
        half_val: 14698
        half_val: 14912
        half_val: 14320
        half_val: 12096
        half_val: 14848
        half_val: 13328
        half_val: 13304
        half_val: 14656
        half_val: 13000
        half_val: 14838
        half_val: 15086
        half_val: 15228
        half_val: 12976
        half_val: 11280
        half_val: 12728
        half_val: 12720
        half_val: 14624
        half_val: 14394
        half_val: 13548
        half_val: 14344
        half_val: 9536
        half_val: 14734
        half_val: 12392
        half_val: 14942
        half_val: 14546
        half_val: 14252
        half_val: 12904
        half_val: 14560
        half_val: 14084
        half_val: 11376
        half_val: 14148
        half_val: 9280
        half_val: 14368
        half_val: 14000
        half_val: 13828
        half_val: 15044
        half_val: 14350
        half_val: 14732
        half_val: 12336
        half_val: 15056
        half_val: 11648
        half_val: 15236
        half_val: 14232
        half_val: 14880
        half_val: 11936
        half_val: 11920
        half_val: 12648
        half_val: 12240
        half_val: 13928
        half_val: 14824
        half_val: 14072
        half_val: 14382
        half_val: 13320
        half_val: 13384
        half_val: 14584
        half_val: 14292
        half_val: 14088
        half_val: 15310
        half_val: 13388
        half_val: 15252
        half_val: 14032
        half_val: 15104
        half_val: 14504
        half_val: 14272
        half_val: 13468
        half_val: 14532
        half_val: 14480
        half_val: 14574
        half_val: 14304
        half_val: 13296
        half_val: 13016
        half_val: 14352
        half_val: 11104
        half_val: 14990
        half_val: 14828
        half_val: 14712
        half_val: 14752
        half_val: 14926
        half_val: 14714
        half_val: 13200
        half_val: 15058
        half_val: 15216
        half_val: 14634
        half_val: 15264
        half_val: 13616
        half_val: 13776
        half_val: 14656
        half_val: 10496
        half_val: 12856
        half_val: 14950
        half_val: 15186
        half_val: 12192
        half_val: 14966
        half_val: 14750
        half_val: 13620
        half_val: 13672
        half_val: 15220
        half_val: 14622
        half_val: 14466
        half_val: 11280
        half_val: 12984
        half_val: 14446
        half_val: 14668
        half_val: 13616
        half_val: 10560
        half_val: 13980
        half_val: 15130
        half_val: 12392
        half_val: 15240
        half_val: 15292
        half_val: 12376
        half_val: 13856
        half_val: 15338
        half_val: 12864
        half_val: 10496
        half_val: 14656
        half_val: 14796
        half_val: 14064
        half_val: 14950
        half_val: 13888
        half_val: 9408
        half_val: 14188
        half_val: 13960
        half_val: 12688
        half_val: 15296
        half_val: 13864
        half_val: 14048
        half_val: 12536
        half_val: 12584
        half_val: 13472
        half_val: 13128
        half_val: 12688
        half_val: 15106
        half_val: 6656
        half_val: 14916
        half_val: 13620
        half_val: 15182
        half_val: 14542
        half_val: 11520
        half_val: 14514
        half_val: 14926
        half_val: 14370
        half_val: 15096
        half_val: 14822
        half_val: 14892
        half_val: 10944
        half_val: 15284
        half_val: 13008
        half_val: 14614
        half_val: 14060
        half_val: 14854
        half_val: 14598
        half_val: 14434
        half_val: 10688
        half_val: 14260
        half_val: 14236
        half_val: 11008
        half_val: 13640
        half_val: 13708
        half_val: 13552
        half_val: 14954
        half_val: 12368
        half_val: 15222
        half_val: 13660
        half_val: 14796
        half_val: 15166
        half_val: 14624
        half_val: 15004
        half_val: 15120
        half_val: 13680
        half_val: 12240
        half_val: 14720
        half_val: 7936
        half_val: 14660
        half_val: 15232
        half_val: 13760
        half_val: 13972
        half_val: 14598
        half_val: 14136
        half_val: 15272
        half_val: 12376
        half_val: 13712
        half_val: 15006
        half_val: 14592
        half_val: 13808
        half_val: 13496
        half_val: 12440
        half_val: 14362
        half_val: 15086
        half_val: 15050
        half_val: 13776
        half_val: 13516
        half_val: 12128
        half_val: 14442
        half_val: 14292
        half_val: 13896
        half_val: 14994
        half_val: 14898
        half_val: 14656
        half_val: 14904
        half_val: 14332
        half_val: 12328
        half_val: 13080
        half_val: 14032
        half_val: 12832
        half_val: 13112
        half_val: 13888
        half_val: 12648
        half_val: 13748
        half_val: 13688
        half_val: 14630
        half_val: 15322
        half_val: 13880
        half_val: 14736
        half_val: 14740
        half_val: 14366
        half_val: 13724
        half_val: 14468
        half_val: 15286
        half_val: 15240
        half_val: 14564
        half_val: 11040
        half_val: 9088
        half_val: 14152
        half_val: 14820
        half_val: 12792
        half_val: 14614
        half_val: 12904
        half_val: 11664
        half_val: 15280
        half_val: 14930
        half_val: 15356
        half_val: 12952
        half_val: 12952
        half_val: 8960
        half_val: 13032
        half_val: 14452
        half_val: 14898
        half_val: 13840
        half_val: 10848
        half_val: 14890
        half_val: 14092
        half_val: 13344
        half_val: 13960
        half_val: 13460
        half_val: 14994
        half_val: 14068
        half_val: 14128
        half_val: 14810
        half_val: 14702
        half_val: 12696
        half_val: 15068
        half_val: 14674
        half_val: 14268
        half_val: 11392
        half_val: 14336
        half_val: 13792
        half_val: 14910
        half_val: 15296
        half_val: 14136
        half_val: 13880
        half_val: 15076
        half_val: 14672
        half_val: 13136
        half_val: 10336
        half_val: 14612
        half_val: 12384
        half_val: 12256
        half_val: 14072
        half_val: 14636
        half_val: 14684
        half_val: 14700
        half_val: 14978
        half_val: 14986
        half_val: 14930
        half_val: 15160
        half_val: 13572
        half_val: 14598
        half_val: 14530
        half_val: 12952
        half_val: 14394
        half_val: 13232
        half_val: 13312
        half_val: 14276
        half_val: 13556
        half_val: 7424
        half_val: 13576
        half_val: 12480
        half_val: 13420
        half_val: 11744
        half_val: 12744
        half_val: 12560
        half_val: 13428
        half_val: 14576
        half_val: 14688
        half_val: 14576
        half_val: 14288
        half_val: 12496
        half_val: 13732
        half_val: 15024
        half_val: 12960
        half_val: 13532
        half_val: 14678
        half_val: 14244
        half_val: 13940
        half_val: 14690
        half_val: 14320
        half_val: 13604
        half_val: 15248
        half_val: 14406
        half_val: 13000
        half_val: 15144
        half_val: 14000
        half_val: 14354
        half_val: 12448
        half_val: 14648
        half_val: 14052
        half_val: 15244
        half_val: 11584
        half_val: 15270
        half_val: 14448
        half_val: 14764
        half_val: 14514
        half_val: 10112
        half_val: 13224
        half_val: 15298
        half_val: 14962
        half_val: 14350
        half_val: 14998
        half_val: 15210
        half_val: 14864
        half_val: 14076
        half_val: 15214
        half_val: 13908
        half_val: 14948
        half_val: 15122
        half_val: 13856
        half_val: 13532
        half_val: 11968
        half_val: 14982
        half_val: 13688
        half_val: 14744
        half_val: 14004
        half_val: 14818
        half_val: 13808
        half_val: 14774
        half_val: 13836
        half_val: 14950
        half_val: 12528
        half_val: 14052
        half_val: 15126
        half_val: 12520
        half_val: 12632
        half_val: 11296
        half_val: 14200
        half_val: 13536
        half_val: 11536
        half_val: 14596
        half_val: 11760
        half_val: 14316
        half_val: 13840
        half_val: 12384
        half_val: 15210
        half_val: 13904
        half_val: 12952
        half_val: 14864
        half_val: 13032
        half_val: 14954
        half_val: 13720
        half_val: 15126
        half_val: 15168
        half_val: 14910
        half_val: 15062
        half_val: 13592
        half_val: 12240
        half_val: 12848
        half_val: 11616
        half_val: 14624
        half_val: 7936
        half_val: 10848
        half_val: 15186
        half_val: 15076
        half_val: 14848
        half_val: 15322
        half_val: 13248
        half_val: 14806
        half_val: 13736
        half_val: 13416
        half_val: 13784
        half_val: 15092
        half_val: 13532
        half_val: 14928
        half_val: 14446
        half_val: 15322
        half_val: 12544
        half_val: 15078
        half_val: 15322
        half_val: 15310
        half_val: 14528
        half_val: 14292
        half_val: 13912
        half_val: 14436
        half_val: 8320
        half_val: 14540
        half_val: 15084
        half_val: 15312
        half_val: 12952
        half_val: 13644
        half_val: 14922
        half_val: 13656
        half_val: 13404
        half_val: 14634
        half_val: 12432
        half_val: 10944
        half_val: 13344
        half_val: 12688
        half_val: 13916
        half_val: 15220
        half_val: 14614
        half_val: 13684
        half_val: 12512
        half_val: 15140
        half_val: 10240
        half_val: 14780
        half_val: 14456
        half_val: 14414
        half_val: 14564
        half_val: 14924
        half_val: 15206
        half_val: 12336
        half_val: 15300
        half_val: 14358
        half_val: 14390
        half_val: 14916
        half_val: 15260
        half_val: 12840
        half_val: 13344
        half_val: 10784
        half_val: 14878
        half_val: 13428
        half_val: 13872
        half_val: 13864
        half_val: 14490
        half_val: 14622
        half_val: 12704
        half_val: 15326
        half_val: 14356
        half_val: 13088
        half_val: 11632
        half_val: 13928
        half_val: 13000
        half_val: 15134
        half_val: 12624
        half_val: 12784
        half_val: 14728
        half_val: 12160
        half_val: 13356
        half_val: 14040
        half_val: 14716
        half_val: 13324
        half_val: 13992
        half_val: 14188
        half_val: 15074
        half_val: 15018
        half_val: 14304
        half_val: 10816
        half_val: 14786
        half_val: 13668
        half_val: 11456
        half_val: 14808
        half_val: 14410
        half_val: 15272
        half_val: 13544
        half_val: 14044
        half_val: 14880
        half_val: 14616
        half_val: 13688
        half_val: 10912
        half_val: 13564
        half_val: 13660
        half_val: 13740
        half_val: 14446
        half_val: 15268
        half_val: 14896
        half_val: 14876
        half_val: 15324
        half_val: 11568
        half_val: 14164
        half_val: 14476
        half_val: 14788
        half_val: 13460
        half_val: 14284
        half_val: 14184
        half_val: 14650
        half_val: 11424
        half_val: 13748
        half_val: 14980
        half_val: 12912
        half_val: 13280
        half_val: 14744
        half_val: 14628
        half_val: 9280
        half_val: 14790
        half_val: 14848
        half_val: 14498
        half_val: 10944
        half_val: 14408
        half_val: 14562
        half_val: 13596
        half_val: 14614
        half_val: 14504
        half_val: 14044
        half_val: 13448
        half_val: 14970
        half_val: 13944
        half_val: 13516
        half_val: 10464
        half_val: 15096
        half_val: 15266
        half_val: 13976
        half_val: 15194
        half_val: 12808
        half_val: 15002
        half_val: 14392
        half_val: 14512
        half_val: 14762
        half_val: 14898
        half_val: 13560
        half_val: 15060
        half_val: 13708
        half_val: 15190
        half_val: 10528
        half_val: 12840
        half_val: 12856
        half_val: 15092
        half_val: 15336
        half_val: 13924
        half_val: 11104
        half_val: 14766
        half_val: 11536
        half_val: 14816
        half_val: 15148
        half_val: 12344
        half_val: 14954
        half_val: 11920
        half_val: 12912
        half_val: 14594
        half_val: 13680
        half_val: 14384
        half_val: 14552
        half_val: 14766
        half_val: 13324
        half_val: 13412
        half_val: 15326
        half_val: 14348
        half_val: 12408
        half_val: 10432
        half_val: 12640
        half_val: 13144
        half_val: 15134
        half_val: 12656
        half_val: 15106
        half_val: 14974
        half_val: 13700
        half_val: 15010
        half_val: 15324
        half_val: 14072
        half_val: 12016
        half_val: 14362
        half_val: 15162
        half_val: 15246
        half_val: 12176
        half_val: 14520
        half_val: 7680
        half_val: 13000
        half_val: 14432
        half_val: 14826
        half_val: 14936
        half_val: 14846
        half_val: 15140
        half_val: 14694
        half_val: 14454
        half_val: 14392
        half_val: 13360
        half_val: 12944
        half_val: 13840
        half_val: 11728
        half_val: 14680
        half_val: 15054
        half_val: 14672
        half_val: 14702
        half_val: 13664
        half_val: 14574
        half_val: 12408
        half_val: 15012
        half_val: 11552
        half_val: 12312
        half_val: 13700
        half_val: 14808
        half_val: 14484
        half_val: 13640
        half_val: 15084
        half_val: 11696
        half_val: 12880
        half_val: 9600
        half_val: 14360
        half_val: 11536
        half_val: 13348
      }
    }
  }
}
node {
  name: "in_0/read"
  op: "Identity"
  input: "in_0"
  attr {
    key: "T"
    value {
      type: DT_HALF
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_0"
      }
    }
  }
}
node {
  name: "in_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_HALF
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_HALF
        tensor_shape {
          dim {
            size: 2
          }
          dim {
            size: 2
          }
          dim {
            size: 2
          }
          dim {
            size: 3
          }
          dim {
            size: 6
          }
        }
        half_val: 6656
        half_val: 14978
        half_val: 14284
        half_val: 12720
        half_val: 11440
        half_val: 13952
        half_val: 15006
        half_val: 14152
        half_val: 12000
        half_val: 15096
        half_val: 13536
        half_val: 13732
        half_val: 14016
        half_val: 14552
        half_val: 14084
        half_val: 15288
        half_val: 14772
        half_val: 15220
        half_val: 13716
        half_val: 14770
        half_val: 13908
        half_val: 14948
        half_val: 14972
        half_val: 14808
        half_val: 14940
        half_val: 11168
        half_val: 13708
        half_val: 15046
        half_val: 13472
        half_val: 12928
        half_val: 14686
        half_val: 14630
        half_val: 14946
        half_val: 14694
        half_val: 15348
        half_val: 13828
        half_val: 12752
        half_val: 14842
        half_val: 13484
        half_val: 14488
        half_val: 13776
        half_val: 14844
        half_val: 13608
        half_val: 12976
        half_val: 14570
        half_val: 8960
        half_val: 14652
        half_val: 15272
        half_val: 14744
        half_val: 9088
        half_val: 14546
        half_val: 12432
        half_val: 15280
        half_val: 14048
        half_val: 8320
        half_val: 14476
        half_val: 12352
        half_val: 14622
        half_val: 14408
        half_val: 15318
        half_val: 14842
        half_val: 13584
        half_val: 14316
        half_val: 12368
        half_val: 14838
        half_val: 15242
        half_val: 14674
        half_val: 13616
        half_val: 14900
        half_val: 14934
        half_val: 14594
        half_val: 9216
        half_val: 12888
        half_val: 15290
        half_val: 14712
        half_val: 13632
        half_val: 13964
        half_val: 14636
        half_val: 15206
        half_val: 14380
        half_val: 15122
        half_val: 7936
        half_val: 14588
        half_val: 12560
        half_val: 14718
        half_val: 12912
        half_val: 13336
        half_val: 15290
        half_val: 14510
        half_val: 12176
        half_val: 15124
        half_val: 14756
        half_val: 14614
        half_val: 15290
        half_val: 14558
        half_val: 15306
        half_val: 14998
        half_val: 14786
        half_val: 14760
        half_val: 13788
        half_val: 9408
        half_val: 11680
        half_val: 15110
        half_val: 12456
        half_val: 14870
        half_val: 13064
        half_val: 15286
        half_val: 13572
        half_val: 14422
        half_val: 15102
        half_val: 14212
        half_val: 15252
        half_val: 14674
        half_val: 14494
        half_val: 10592
        half_val: 15018
        half_val: 13440
        half_val: 13696
        half_val: 14552
        half_val: 14528
        half_val: 12656
        half_val: 11344
        half_val: 13840
        half_val: 13016
        half_val: 15028
        half_val: 12768
        half_val: 12632
        half_val: 14376
        half_val: 13984
        half_val: 14842
        half_val: 11136
        half_val: 14694
        half_val: 15212
        half_val: 10048
        half_val: 13592
        half_val: 14000
        half_val: 14346
        half_val: 14342
        half_val: 15312
        half_val: 13408
        half_val: 13944
        half_val: 15054
        half_val: 9792
        half_val: 9536
      }
    }
  }
}
node {
  name: "in_1/read"
  op: "Identity"
  input: "in_1"
  attr {
    key: "T"
    value {
      type: DT_HALF
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_1"
      }
    }
  }
}
node {
  name: "Conv3DBackpropInputV2/input_sizes"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 5
          }
        }
        tensor_content: "\001\000\000\000\020\000\000\000\020\000\000\000\020\000\000\000\003\000\000\000"
      }
    }
  }
}
node {
  name: "Conv3DBackpropInputV2"
  op: "Conv3DBackpropInputV2"
  input: "Conv3DBackpropInputV2/input_sizes"
  input: "in_1/read"
  input: "in_0/read"
  attr {
    key: "T"
    value {
      type: DT_HALF
    }
  }
  attr {
    key: "Tshape"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "data_format"
    value {
      s: "NDHWC"
    }
  }
  attr {
    key: "dilations"
    value {
      list {
        i: 1
        i: 1
        i: 1
        i: 1
        i: 1
      }
    }
  }
  attr {
    key: "padding"
    value {
      s: "VALID"
    }
  }
  attr {
    key: "strides"
    value {
      list {
        i: 1
        i: 2
        i: 2
        i: 2
        i: 1
      }
    }
  }
}
library {
}
