node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
          }
          dim {
          }
          dim {
          }
        }
      }
    }
  }
}
node {
  name: "adjust_contrast/images"
  op: "Pack"
  input: "Const"
  attr {
    key: "N"
    value {
      i: 1
    }
  }
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "axis"
    value {
      i: 0
    }
  }
}
node {
  name: "adjust_contrast/contrast_factor"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 0.0
      }
    }
  }
}
node {
  name: "adjust_contrast"
  op: "AdjustContrastv2"
  input: "adjust_contrast/images"
  input: "adjust_contrast/contrast_factor"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
node {
  name: "adjust_contrast/Identity"
  op: "Identity"
  input: "adjust_contrast"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
library {
}
