node {
  name: "in_0"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_HALF
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_HALF
        tensor_shape {
          dim {
            size: 3
          }
          dim {
            size: 4
          }
        }
        half_val: 14974
        half_val: 13976
        half_val: 11504
        half_val: 14280
        half_val: 14830
        half_val: 14870
        half_val: 12528
        half_val: 14434
        half_val: 14996
        half_val: 13104
        half_val: 7424
        half_val: 14636
      }
    }
  }
}
node {
  name: "in_0/read"
  op: "Identity"
  input: "in_0"
  attr {
    key: "T"
    value {
      type: DT_HALF
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_0"
      }
    }
  }
}
node {
  name: "in_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_HALF
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_HALF
        tensor_shape {
          dim {
            size: 3
          }
        }
        half_val: 6656
        half_val: 14978
        half_val: 14284
      }
    }
  }
}
node {
  name: "in_1/read"
  op: "Identity"
  input: "in_1"
  attr {
    key: "T"
    value {
      type: DT_HALF
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_1"
      }
    }
  }
}
node {
  name: "in_2"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 0
      }
    }
  }
}
node {
  name: "in_2/read"
  op: "Identity"
  input: "in_2"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_2"
      }
    }
  }
}
node {
  name: "NonMaxSuppressionV5/iou_threshold"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_HALF
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_HALF
        tensor_shape {
        }
        half_val: 14336
      }
    }
  }
}
node {
  name: "NonMaxSuppressionV5/score_threshold"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_HALF
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_HALF
        tensor_shape {
        }
        half_val: 14336
      }
    }
  }
}
node {
  name: "NonMaxSuppressionV5/soft_nms_sigma"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_HALF
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_HALF
        tensor_shape {
        }
        half_val: 0
      }
    }
  }
}
node {
  name: "NonMaxSuppressionV5"
  op: "NonMaxSuppressionV5"
  input: "in_0/read"
  input: "in_1/read"
  input: "in_2/read"
  input: "NonMaxSuppressionV5/iou_threshold"
  input: "NonMaxSuppressionV5/score_threshold"
  input: "NonMaxSuppressionV5/soft_nms_sigma"
  attr {
    key: "T"
    value {
      type: DT_HALF
    }
  }
  attr {
    key: "pad_to_max_output_size"
    value {
      b: false
    }
  }
}
library {
}
