node {
  name: "Variable"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_BOOL
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_BOOL
        tensor_shape {
          dim {
            size: 8
          }
        }
        bool_val: true
        bool_val: true
        bool_val: true
        bool_val: false
        bool_val: true
        bool_val: false
        bool_val: true
        bool_val: true
      }
    }
  }
}
node {
  name: "Variable/read"
  op: "Identity"
  input: "Variable"
  attr {
    key: "T"
    value {
      type: DT_BOOL
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@Variable"
      }
    }
  }
}
node {
  name: "CompareAndBitpack/threshold"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_BOOL
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_BOOL
        tensor_shape {
        }
        bool_val: true
      }
    }
  }
}
node {
  name: "CompareAndBitpack"
  op: "CompareAndBitpack"
  input: "Variable/read"
  input: "CompareAndBitpack/threshold"
  attr {
    key: "T"
    value {
      type: DT_BOOL
    }
  }
}
library {
}
