node {
  name: "in_0"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_HALF
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_HALF
        tensor_shape {
          dim {
            size: 1
          }
          dim {
            size: 10
          }
        }
        half_val: 47454
        half_val: 13095
        half_val: 14945
        half_val: 11816
        half_val: 14793
        half_val: 13673
        half_val: 47575
        half_val: 15179
        half_val: 47123
        half_val: 15309
      }
    }
  }
}
node {
  name: "in_0/read"
  op: "Identity"
  input: "in_0"
  attr {
    key: "T"
    value {
      type: DT_HALF
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@in_0"
      }
    }
  }
}
node {
  name: "Abs"
  op: "Abs"
  input: "in_0/read"
  attr {
    key: "T"
    value {
      type: DT_HALF
    }
  }
}
library {
}
